HCH.Web/Models/ProfileViewModel.cs
using HCH.Models.Common;
using System.ComponentModel.DataAnnotations;

namespace HCH.Web.Models
{
    public class ProfileViewModel
    {
        public string Id { get; set; }

        [Required]
        [Display(Name = "Наименование")]
        [MinLength(CommonConstants.NameMinLength, ErrorMessage = "Наименованието трябва да е поне {1} символа.")]
        public string Name { get; set; }

        [Required]
        [Display(Name = "Описание")]
        [MinLength(CommonConstants.ProfileDescriptionMinLength, ErrorMessage = "Описанието трябва да е поне {1} символа.")]
        public string Description { get; set; }
    }
}

HCH.Web/Areas/Admin/Controllers/ProfilesController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using HCH.Web.Models;
using HCH.Services;
using Microsoft.Extensions.Options;
using Microsoft.AspNetCore.Authorization;
using AutoMapper;

namespace HCH.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class ProfilesController : Controller
    {
        private readonly IProfilesService profilesService;
        private readonly IUsersService usersService;
        private readonly IOptions<UserRoles> configRoles;
        private readonly IMapper mapper;

        public ProfilesController(
            IProfilesService profilesService,
            IUsersService usersService,
            IOptions<UserRoles> configRoles,
            IMapper mapper)
        {
            this.profilesService = profilesService;
            this.usersService = usersService;
            this.configRoles = configRoles;
            this.mapper = mapper;
        }

        // GET: Admin/Profiles/Index_Admin
        public async Task<IActionResult> Index_Admin()
        {
            var profiles = await this.profilesService.All();

            var viewProfiles = profiles.Select(x => this.mapper.Map<ProfileViewModel>(x));

            return View(viewProfiles);
        }

        // GET: Admin/Profiles/Details/5        
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            HCH.Models.Profile profile = await this.profilesService.GetProfileById(id);

            if (profile == null)
            {
                return NotFound();
            }

            var profileView = this.mapper.Map<ProfileDetailsViewModel>(profile);

            return View(profileView);
        }

        // GET: Admin/Profiles/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Profiles/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ProfileDetailsViewModel profileViewModel)
        {
            if (ModelState.IsValid)
            {
                var profile = this.mapper.Map<HCH.Models.Profile>(profileViewModel);
                
                await this.profilesService.AddProfileAsync(profile);
                return RedirectToAction(nameof(Index_Admin));
            }
            return View(profileViewModel);
        }

        // GET: Admin/Profiles/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var profile = await this.profilesService.GetProfileById(id);

            if (profile == null)
            {
                return NotFound();
            }

            var profileView = this.mapper.Map<ProfileDetailsViewModel>(profile);

            return View(profileView);
        }

        // POST: Admin/Profiles/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, ProfileDetailsViewModel profile)
        {
            if (id != profile.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await this.profilesService.UpdateProfileAsync(id, profile.Name, profile.Description);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!this.profilesService.ProfileExists(profile.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index_Admin));
            }
            return View(profile);
        }

        // GET: Admin/Profiles/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {return NotFound();
            }

            HCH.Models.Profile profile = await this.profilesService.GetProfileById(id);

            if (profile == null)
            {
                return NotFound();
            }

            var profileView = this.mapper.Map<ProfileDetailsViewModel>(profile);

            return View(profileView);
        }

        // POST: Admin/Profiles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            await this.profilesService.RemoveProfileAsync(id);
            
            return RedirectToAction(nameof(Index_Admin));
        }        
    }
}

HCH.Web/Controllers/ProfilesController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using HCH.Web.Models;
using HCH.Services;
using Microsoft.Extensions.Options;
using AutoMapper;

namespace HCH.Web.Controllers
{
    public class ProfilesController : Controller
    {
        private readonly IProfilesService profilesService;
        private readonly IUsersService usersService;
        private readonly IOptions<UserRoles> configRoles;
        private readonly IMapper mapper;

        public ProfilesController(
            IProfilesService profilesService,
            IUsersService usersService,
            IOptions<UserRoles> configRoles,
            IMapper mapper)
        {
            this.profilesService = profilesService;
            this.usersService = usersService;
            this.configRoles = configRoles;
            this.mapper = mapper;
        }

        // GET: Profiles
        public async Task<IActionResult> Index()
        {
            var profiles = await this.profilesService.All();

            var viewProfiles = profiles.Select(x => this.mapper.Map<ProfileViewModel>(x));

            foreach (var item in viewProfiles)
            {
                if (item.Description.Length > 100)
                {
                    item.Description = item.Description.Substring(0, 100);
                }
                
            }

            return View(viewProfiles);
        }

        // GET: Profiles/Details/5        
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var profile = await this.profilesService.GetProfileById(id);

            if (profile == null)
            {
                return NotFound();
            }

            var profileView = this.mapper.Map<ProfileDetailsViewModel>(profile);

            return View(profileView);
        }
    }
}

HCH.Web/Controllers/TherapistsController.cs
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using HCH.Services;
using HCH.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace HCH.Web.Controllers
{
    public class TherapistsController : Controller
    {
        private readonly ITherapistsService therapistsService;
        private readonly IProfilesService profilesService;
        private readonly IMapper mapper;

        public TherapistsController(
            ITherapistsService therapistsService,
            IProfilesService profilesService,
            IMapper mapper)
        {
            this.therapistsService = therapistsService;
            this.profilesService = profilesService;
            this.mapper = mapper;
        }

        public async Task<IActionResult> Index(string profile)
        {
            var therapists = await this.therapistsService.GetTherapistsByProfile(profile);
            var therapistsView = therapists.ToList()
                .Select(x => this.mapper.Map<TherapistViewModel>(x));

            ViewData["Profile"] = profile;

            return View(therapistsView);
        }

    }
}

HCH.Web/Views/Profiles/Details.cshtml
@model HCH.Web.Models.ProfileDetailsViewModel

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container">
    <h4>@Model.Name</h4>
    <hr />
    <p>@Model.Description</p>
    <hr />

    <div class="container mt-2">
        <a asp-area="" asp-controller="Therapists" asp-action="Index" asp-route-profile="@Model.Name"><h5>Изберете терапевт</h5></a>
        <a asp-area="" asp-controller="Profiles" asp-action="Index"><h5>Към списъка</h5></a>
    </div>
    
</div>

HCH.Web/Views/Profiles/Index.cshtml
@model IEnumerable<HCH.Web.Models.ProfileViewModel>


@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<main class="mt-3">
    <div class="container">
        <div class="row">
        <div class="col-md-3">
            <h3>Изберете терапевт</h3>
            <hr class="hr-4" />
            @foreach (var item in Model)
            {
                <div class="container mt-2">
                    <a asp-controller="Therapists" asp-action="Index" asp-route-profile="@item.Name"><h4>@item.Name</h4></a>
                </div>
            }
        </div>
        <div class="col-md-9">
            <h3>Запознайте се с методите, които предлагаме</h3>
            <hr class="hr-4" />

            @foreach (var item in Model)
            {
                <div class="card mt-5">
                    <div class="card-body">
                        <h3 class="card-title">@item.Name</h3>
                        <p class="card-text">@item.Description</p>
                    </div>
                    <div class="card-footer">
                        <a asp-controller="Profiles" asp-action="Details" asp-route-id="@item.Id" class="card-link">Вижте повече</a>
                    </div>
                </div>
                <hr class="hr-4" />
            }

        </div>
    </div>
    <hr class="hr-4 mb-0" />
    </div>
</main>

HCH.Web/Views/Profiles/Index_Admin.cshtml
@model IEnumerable<HCH.Web.Models.ProfileViewModel>

@{
    ViewData["Title"] = "Index_Admin";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<main class="mt-3">

    <div class="container-fluid">
        <div class="col-md-3">
            <h3>Терапевти</h3>
            <hr class="hr-4" />
            @foreach (var item in Model)
            {
                <div class="container mt-2">
                    <a asp-controller="Therapists" asp-action="Index_Admin" asp-route-profile="@item.Name"><h4>@item.Name</h4></a>
                </div>
            }
        </div>
        <div class="col-md-9">
            <h3>Профили</h3>
            <hr class="hr-4" />

            <a class="a-black dropdown-item" asp-controller="Profiles" asp-action="Create">Създай профил</a>
            <hr class="hr-4" />
            @foreach (var item in Model)
            {
                <div class="card mt-5">
                    <div class="card-body">
                        <h3 class="card-title">@item.Name</h3>
                        <p class="card-text">@item.Description</p>
                    </div>
                    <div class="card-footer">
                        <a asp-controller="Profiles" asp-action="Details" asp-route-id="@item.Id" class="card-link">Вижте повече</a>
                    </div>
                    <div class="card-footer">
                        <a asp-controller="Profiles" asp-action="Edit" asp-route-id="@item.Id" class="card-link">Редактирай</a>
                    </div>
                    <div class="card-footer">
                        <a asp-controller="Profiles" asp-action="Delete" asp-route-id="@item.Id" class="card-link">Изтрий</a>
                    </div>
                </div>
                <hr class="hr-4" />
            }

        </div>
    </div>
    <hr class="hr-4 mb-0" />

</main>