HCH.Web/Models/UserViewModel.cs
namespace HCH.Web.Models
{
    public class UserViewModel
    {
        public string Id { get; set; }

        public string UserName { get; set; }

        public string Role { get; set; }

        public string Profile { get; set; }
    }
}

HCH.Web/Areas/Admin/Controllers/UsersController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using HCH.Services;
using HCH.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;

namespace HCH.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class UsersController : Controller
    {
        private readonly IUsersService usersService;
        private readonly IMapper mapper;
        private readonly IOptions<UserRoles> config;

        public UsersController(IUsersService usersService,
            IMapper mapper,
            IOptions<UserRoles> config)
        {
            this.usersService = usersService;
            this.mapper = mapper;
            this.config = config;
        }

        public async Task<IActionResult> Index()
        {
            var users = await this.usersService.AllAsync();

            var currentUsername = this.User.Identity.Name;

            var viewUsers = new List<UserViewModel>();

            foreach (var user in users)
            {
                var userRoles = this.usersService.GetRolesAsync(user);

                var viewUser = this.mapper.Map<UserViewModel>(user);

                viewUser.Role = string.Join(", ", userRoles);

                viewUsers.Add(viewUser);
            }

            var currentUser = viewUsers.FirstOrDefault(x => x.UserName == currentUsername);

            viewUsers.Remove(currentUser);

            return View(viewUsers.OrderByDescending(x => x.Role.Length));
        }

        public async Task<IActionResult> AddAdminRole(string id)
        {
            var user = this.usersService.GetUserById(id);

            var userRoles = this.usersService.GetRolesAsync(user);

            var adminRole = config.Value.AdminRole;

            if (!userRoles.Contains(adminRole))
            {
                await this.usersService.AddToRoleAsync(user, adminRole);
            }
            
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> RemoveAdminRole(string id)
        {
            var user = this.usersService.GetUserById(id);

            var userRoles = this.usersService.GetRolesAsync(user);

            if (userRoles.Contains(config.Value.AdminRole))
            {
                await this.usersService.RemoveFromRoleAsync(user, config.Value.AdminRole);
            }

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> AddTherapistRole(string id)
        {
            var user = this.usersService.GetUserById(id);

            var userRoles = this.usersService.GetRolesAsync(user);

            var therapistRole = config.Value.TherapistRole;

            if (!userRoles.Contains(therapistRole))
            {
                await this.usersService.AddToRoleAsync(user, therapistRole);
            }

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> RemoveTherapistRole(string id)
        {
            var user = this.usersService.GetUserById(id);

            var userRoles = this.usersService.GetRolesAsync(user);

            if (userRoles.Contains(config.Value.TherapistRole))
            {
                await this.usersService.RemoveFromRoleAsync(user, config.Value.TherapistRole);
            }

            return RedirectToAction("Index");
        }
    }
}

HCH.Web/Controllers/TherapistsController.cs
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using HCH.Services;
using HCH.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace HCH.Web.Controllers
{
    public class TherapistsController : Controller
    {
        private readonly ITherapistsService therapistsService;
        private readonly IProfilesService profilesService;
        private readonly IMapper mapper;

        public TherapistsController(
            ITherapistsService therapistsService,
            IProfilesService profilesService,
            IMapper mapper)
        {
            this.therapistsService = therapistsService;
            this.profilesService = profilesService;
            this.mapper = mapper;
        }

        public async Task<IActionResult> Index(string profile)
        {
            var therapists = await this.therapistsService.GetTherapistsByProfile(profile);
            var therapistsView = therapists.ToList()
                .Select(x => this.mapper.Map<TherapistViewModel>(x));

            ViewData["Profile"] = profile;

            return View(therapistsView);
        }

    }
}

HCH.Web/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using HCH.Services;
using HCH.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;

namespace HCH.Web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UsersController : Controller
    {
        private readonly IUsersService usersService;
        private readonly IMapper mapper;
        private readonly IOptions<UserRoles> config;

        public UsersController(IUsersService usersService,
            IMapper mapper,
            IOptions<UserRoles> config)
        {
            this.usersService = usersService;
            this.mapper = mapper;
            this.config = config;
        }

        public async Task<IActionResult> Index()
        {
            var users = await this.usersService.AllAsync();

            var currentUsername = this.User.Identity.Name;

            var viewUsers = new List<UserViewModel>();

            foreach (var user in users)
            {
                var userRoles = this.usersService.GetRolesAsync(user);

                var viewUser = this.mapper.Map<UserViewModel>(user);

                viewUser.Role = string.Join(", ", userRoles);

                viewUsers.Add(viewUser);
            }

            var currentUser = viewUsers.FirstOrDefault(x => x.UserName == currentUsername);

            viewUsers.Remove(currentUser);

            return View(viewUsers);
        }

        public async Task<IActionResult> AddAdminRole(string id)
        {
            var user = this.usersService.GetUserById(id);

            var userRoles = this.usersService.GetRolesAsync(user);

            var adminRole = config.Value.AdminRole;

            if (!userRoles.Contains(adminRole))
            {
                await this.usersService.AddToRoleAsync(user, adminRole);
            }
            
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> RemoveAdminRole(string id)
        {
            var user = this.usersService.GetUserById(id);

            var userRoles = this.usersService.GetRolesAsync(user);

            if (userRoles.Contains(config.Value.AdminRole))
            {
                await this.usersService.RemoveFromRoleAsync(user, config.Value.AdminRole);
            }

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> AddTherapistRole(string id)
        {
            var user = this.usersService.GetUserById(id);

            var userRoles = this.usersService.GetRolesAsync(user);

            var therapistRole = config.Value.TherapistRole;

            if (!userRoles.Contains(therapistRole))
            {
                await this.usersService.AddToRoleAsync(user, therapistRole);
            }

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> RemoveTherapistRole(string id)
        {
            var user = this.usersService.GetUserById(id);

            var userRoles = this.usersService.GetRolesAsync(user);

            if (userRoles.Contains(config.Value.TherapistRole))
            {
                await this.usersService.RemoveFromRoleAsync(user, config.Value.TherapistRole);
            }

            return RedirectToAction("Index");
        }
    }
}

HCH.Web/Areas/Admin/Views/Users/Index.cshtml
@model IEnumerable<HCH.Web.Models.UserViewModel>

    @{
    ViewData["Title"] = "User_Administration";
    Layout = "~/Views/Shared/_Layout.cshtml";
    }


    <main class="mt-3">
        <div class="container justify-content-center">
            <h1 class="text-center">Всички потребители</h1>
            <hr class="hr-4" />
            <div class="container-fluid">
                <table class="table  mx-auto table-hover">
                    <thead>
                        <tr class="row">
                            <th class="col-md-1 text-center">#</th>
                            <th class="col-md-1 text-center">Потребителско име</th>
                            <th class="col-md-3 text-center">Роли</th>
                            <th class="col-md-2 text-center">Профил</th>
                            <th class="col-md-5 text-center">Добави роля</th>
                        </tr>
                    </thead>
                    <tbody>
                        @{ int count = 0;}
                        @foreach (var item in Model)
                    {
                        count++;

                        <tr class="row">
                            <th class="col-md-1 text-center">@count</th>
                            <td class="col-md-1 text-center">@item.UserName</td>
                            <td class="col-md-3 text-center">@item.Role</td>
                            <td class="col-md-2 text-center">
                                <a asp-area="Admin" asp-controller="Therapists" asp-action="Index_Admin" asp-route-profile="@item.Profile"><h4>@item.Profile</h4></a>
                                
                            </td>
                            <td class="col-md-5 text-center">
                                <div class="container-fluid d-flex justify-content-between">
                                    <form class="form-inline" asp-controller="Therapists" asp-action="Add" asp-route-id="@item.Id" method="get">

                                        <a asp-area="Admin" asp-controller="Users" asp-action="AddAdminRole" asp-route-id="@item.Id" class="btn harmony-bg-color text-center">Admin</a>
                                        <a asp-area="Admin" asp-controller="Users" asp-action="RemoveAdminRole" asp-route-id="@item.Id" class="btn harmony-bg-color">RemoveAdmin</a>
                                                                               
                                        <button type="submit" class="btn harmony-bg-color ml-2">Направи терапевт</button>

                                    </form>
                                </div>
                                    
                            </td>
                        </tr>
                    }
                    </tbody>
                </table>

            </div>
            <hr class="hr-4 mb-0" />
        </div>
    </main>