HCH.Web/Models/TreatmentViewModel.cs
using HCH.Models.Common;
using System;
using System.ComponentModel.DataAnnotations;

namespace HCH.Web.Models
{
    public class TreatmentViewModel
    {
        public string Id { get; set; }
        
                
        public string Profile { get; set; }

        [Required]
        public string ProfileId { get; set; }

        [Required]
        [Display(Name = "Наименование")]
        [MinLength(CommonConstants.NameMinLength, ErrorMessage = "Наименованието трябва да е поне 3 символа.")]
        public string Name { get; set; }

        [Display(Name = "Описание")]
        [MinLength(3, ErrorMessage = "Описанието трябва да е поне 3 символа.")]
        public string Description { get; set; }

        [Required]
        [DataType(DataType.Currency)]
        [Range(0.01, Double.MaxValue, ErrorMessage = "Цената трябва да е по-голяма от 0.")]
        [Display(Name = "Цена в лв.")]        
        public decimal Price { get; set; }
    }
}

HCH.Web/Areas/Therapist/Controllers/TreatmentsController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using HCH.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using HCH.Services;
using HCH.Web.Models;
using AutoMapper;
using X.PagedList;

namespace HCH.Web.Areas.Therapist.Controllers
{
    [Area("Therapist")]
    [Authorize(Roles = "Therapist")]
    public class TreatmentsController : Controller
    {
        private readonly ITreatmentsService treatmentsService;
        private readonly IProfilesService profilesService;
        private readonly SignInManager<HCHWebUser> signInManager;
        private readonly IMapper mapper;

        public TreatmentsController(
            ITreatmentsService treatmentsService,
            IProfilesService profilesService,
            SignInManager<HCHWebUser> signInManager,
            IMapper mapper)
        {
            this.treatmentsService = treatmentsService;
            this.profilesService = profilesService;
            this.signInManager = signInManager;
            this.mapper = mapper;
        }
        
        // GET: Therapist/Treatments/Index_Therapist
        public async Task<IActionResult> Index_Therapist(int? page)
        {
            var therapist = await this.signInManager.UserManager.GetUserAsync(User);

            var profileId = therapist.ProfileId;            

            var treatments = await this.treatmentsService.AllFromProfileAsync(profileId);

            var treatmentsView = treatments
                .Select(x => this.mapper.Map<TreatmentViewModel>(x));

            var profile = await this.profilesService.GetProfileById(profileId);

            var numberOfItems = 8;

            var pageNumber = page ?? 1;

            var onePageOfTreatments = treatmentsView.ToPagedList(pageNumber, numberOfItems);

            ViewBag.PageNumber = pageNumber;

            ViewBag.NumberOfItems = numberOfItems;

            ViewData["ProfileName"] = profile.Name;

            return View(onePageOfTreatments);
        }

        // GET: Therapist/Treatments/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var treatment = await this.treatmentsService.GetTreatmentById(id);

            if (treatment == null)
            {
                return NotFound();
            }

            var treatmentView = this.mapper.Map<TreatmentViewModel>(treatment);

            return View(treatmentView);
        }

        // GET: Therapist/Treatments/Create
        [Authorize(Roles = "Therapist")]
        public IActionResult Create()
        {
            var therapist = this.signInManager.UserManager.GetUserAsync(User).Result;

            ViewData["ProfileId"] = therapist.ProfileId;
            ViewData["ProfileName"] = therapist.Profile.Name;

            return View();
        }

        // POST: Therapist/Treatments/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(TreatmentViewModel treatmentView)
        {
            if (ModelState.IsValid)
            {
                Treatment treatment = this.mapper.Map<Treatment>(treatmentView);

                await this.treatmentsService.AddTreatmentAsync(treatment);
                
                return RedirectToAction(nameof(Index_Therapist));
            }

            var therapist = this.signInManager.UserManager.GetUserAsync(User).Result;

            ViewData["ProfileId"] = therapist.ProfileId;
            ViewData["ProfileName"] = therapist.Profile.Name;

            return View(treatmentView);
        }

        // GET: Therapist/Treatments/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var treatment = await this.treatmentsService.GetTreatmentById(id);

            if (treatment == null)
            {
                return NotFound();
            }

            var treatmentView = this.mapper.Map<TreatmentViewModel>(treatment);

            ViewData["ProfileId"] = treatment.ProfileId;

            var profile = await this.profilesService.GetProfileById(treatment.ProfileId);

            ViewData["ProfileName"] = profile.Name;

            return View(treatmentView);
        }

        // POST: Therapist/Treatments/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, TreatmentViewModel treatmentView)
        {
            if (id != treatmentView.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var treatment = this.mapper.Map<Treatment>(treatmentView);

                try
                {
                    await this.treatmentsService.UpdateTreatmentAsync(treatment);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TreatmentExists(treatmentView.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index_Therapist));
            }
            ViewData["ProfileId"] = treatmentView.ProfileId;

            var profile = await this.profilesService.GetProfileById(treatmentView.ProfileId);

            ViewData["ProfileName"] = profile.Name;

            return View(treatmentView);
        }

        

        // GET: Therapist/Treatments/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var treatment = await this.treatmentsService.GetTreatmentById(id);

            if (treatment == null)
            {
                return NotFound();
            }

            var treatmentView = this.mapper.Map<TreatmentViewModel>(treatment);

            return View(treatmentView);
        }

        // POST: Therapist/Treatments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var treatment = await this.treatmentsService.GetTreatmentById(id);

            await this.treatmentsService.RemoveTreatmentAsync(treatment);
            
            return RedirectToAction(nameof(Index_Therapist));
        }

        private bool TreatmentExists(string id)
        {
            return this.treatmentsService.TreatementExists(id);                
        }
    }
}

HCH.Web/Controllers/TreatmentsController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using HCH.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using HCH.Services;
using HCH.Web.Models;
using AutoMapper;

namespace HCH.Web.Controllers
{
    public class TreatmentsController : Controller
    {
        private readonly ITreatmentsService treatmentsService;
        private readonly IProfilesService profilesService;
        private readonly SignInManager<HCHWebUser> signInManager;
        private readonly IMapper mapper;

        public TreatmentsController(
            ITreatmentsService treatmentsService,
            IProfilesService profilesService,
            SignInManager<HCHWebUser> signInManager,
            IMapper mapper)
        {
            this.treatmentsService = treatmentsService;
            this.profilesService = profilesService;
            this.signInManager = signInManager;
            this.mapper = mapper;
        }
        
        // GET: Treatments/Index_Therapist
        [Authorize(Roles="Therapist")]
        public async Task<IActionResult> Index_Therapist()
        {
            var therapist = await this.signInManager.UserManager.GetUserAsync(User);

            var profileId = therapist.ProfileId;            

            var treatments = await this.treatmentsService.AllFromProfileAsync(profileId);

            var treatmentsView = treatments
                .Select(x => this.mapper.Map<TreatmentViewModel>(x));

            var profile = await this.profilesService.GetProfileById(profileId);

            ViewData["ProfileName"] = profile.Name;

            return View(treatmentsView);
        }

        // GET: Treatments/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var treatment = await this.treatmentsService.GetTreatmentById(id);

            if (treatment == null)
            {
                return NotFound();
            }

            var treatmentView = this.mapper.Map<TreatmentViewModel>(treatment);

            return View(treatmentView);
        }

        // GET: Treatments/Create
        [Authorize(Roles = "Therapist")]
        public IActionResult Create()
        {
            var therapist = this.signInManager.UserManager.GetUserAsync(User).Result;

            ViewData["ProfileId"] = therapist.ProfileId;
            ViewData["ProfileName"] = therapist.Profile.Name;

            return View();
        }

        // POST: Treatments/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Therapist")]
        public async Task<IActionResult> Create(TreatmentViewModel treatmentView)
        {
            if (ModelState.IsValid)
            {
                Treatment treatment = this.mapper.Map<Treatment>(treatmentView);

                await this.treatmentsService.AddTreatmentAsync(treatment);
                
                return RedirectToAction(nameof(Index_Therapist));
            }

            var therapist = this.signInManager.UserManager.GetUserAsync(User).Result;

            ViewData["ProfileId"] = therapist.ProfileId;
            ViewData["ProfileName"] = therapist.Profile.Name;

            return View(treatmentView);
        }

        // GET: Treatments/Edit/5
        [Authorize(Roles = "Therapist")]
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var treatment = await this.treatmentsService.GetTreatmentById(id);

            if (treatment == null)
            {
                return NotFound();
            }

            var treatmentView = this.mapper.Map<TreatmentViewModel>(treatment);

            ViewData["ProfileId"] = treatment.ProfileId;

            var profile = await this.profilesService.GetProfileById(treatment.ProfileId);

            ViewData["ProfileName"] = profile.Name;

            return View(treatmentView);
        }

        // POST: Treatments/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Therapist")]
        public async Task<IActionResult> Edit(string id, TreatmentViewModel treatmentView)
        {
            if (id != treatmentView.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var treatment = this.mapper.Map<Treatment>(treatmentView);

                try
                {
                    await this.treatmentsService.UpdateTreatmentAsync(treatment);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TreatmentExists(treatmentView.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index_Therapist));
            }
            ViewData["ProfileId"] = treatmentView.ProfileId;

            var profile = await this.profilesService.GetProfileById(treatmentView.ProfileId);

            ViewData["ProfileName"] = profile.Name;

            return View(treatmentView);
        }

        

        // GET: Treatments/Delete/5
        [Authorize(Roles = "Therapist")]
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var treatment = await this.treatmentsService.GetTreatmentById(id);

            if (treatment == null)
            {
                return NotFound();
            }

            var treatmentView = this.mapper.Map<TreatmentViewModel>(treatment);

            return View(treatmentView);
        }

        // POST: Treatments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Therapist")]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var treatment = await this.treatmentsService.GetTreatmentById(id);

            await this.treatmentsService.RemoveTreatmentAsync(treatment);
            
            return RedirectToAction(nameof(Index_Therapist));
        }

        private bool TreatmentExists(string id)
        {
            return this.treatmentsService.TreatementExists(id);                
        }
    }
}

HCH.Web/Views/Treatments/Create.cshtml
@model HCH.Web.Models.TreatmentViewModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <h3>Създай</h3>
    <h4>Лечебно средство</h4>
    <h4>Профил @ViewData["ProfileName"]</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="form-group">
                    <input type="hidden" asp-for="ProfileId" value="@ViewData["ProfileId"]">
                </div>

                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <input asp-for="Description" class="form-control" />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Price" class="control-label"></label>
                    <input asp-for="Price" class="form-control" />
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn harmony-bg-color" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-area="" asp-controller="Treatments" asp-action="Index_Therapist">Към списъка</a>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HCH.Web/Views/Treatments/Delete.cshtml
@model HCH.Web.Models.TreatmentViewModel

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">

    <h3>Изтриване на лечебно средство</h3>
    <h3>Профил @Model.Profile</h3>

    <div>

        <hr />
        <dl class="dl-horizontal">
            
            <dt>
                Наименование
            </dt>
            <dd>
                @Model.Name
            </dd>
            <dt>
                Описание
            </dt>
            <dd>
                @Model.Description
            </dd>
            <dt>
                Цена
            </dt>
            <dd>
                @Model.Price лв.
            </dd>
        </dl>

        <form asp-action="Delete">
            <input type="hidden" asp-for="Id" />
            <input type="submit" value="Изтрий" class="btn btn-default" /> |
            <a asp-area="" asp-controller="Treatments" asp-action="Index_Therapist">Към списъка</a>
        </form>
    </div>
</div>

HCH.Web/Views/Treatments/Details.cshtml
@model HCH.Web.Models.TreatmentViewModel

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <h3>Детайли за лечебно средство</h3>
    <div>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                Профил
            </dt>
            <dd>
                @Model.Profile
            </dd>
            <dt>
                Наименование
            </dt>
            <dd>
                @Model.Name
            </dd>
            <dt>
                Описание
            </dt>
            <dd>
                @Model.Description
            </dd>
            <dt>
                Цена
            </dt>
            <dd>
                @Model.Price лв.
            </dd>
        </dl>
    </div>
    <div>
        <a asp-area="" asp-controller="Treatments" asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
        <a asp-area="" asp-controller="Treatments" asp-action="Index_Therapist">Към списъка</a>
    </div>
</div>

HCH.Web/Views/Treatments/Edit.cshtml
@model HCH.Web.Models.TreatmentViewModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <h4>Редактиране на лечебно средство</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id" />
                <input type="hidden" asp-for="ProfileId" value="@Model.ProfileId"/>

                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <input asp-for="Description" class="form-control" />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Price" class="control-label"></label>
                    <input asp-for="Price" class="form-control" />
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Save" class="btn harmony-bg-color" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-area="" asp-controller="Treatments" asp-action="Index_Therapist">Към списъка</a>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HCH.Web/Views/Treatments/Index_Therapist.cshtml
@model IEnumerable<HCH.Web.Models.TreatmentViewModel>

@{
    ViewData["Title"] = "Index_Therapist";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<main class="mt-3">
    <div class="container w-75 justify-content-center">
        <h3 class="text-center">Лечебни средства</h3>
        <h3 class="text-center">Профил @ViewData["ProfileName"]</h3>
        <hr class="hr-4" />
        <div class="container-fluid">

            <div><a asp-area="" asp-controller="Treatments" asp-action="Create">Добави</a></div>

            <table class="table  mx-auto table-hover">
                <thead>
                    <tr class="row">
                        <th class="col-md-1">#</th>
                        <th class="col-md-2">Наименование</th>
                        <th class="col-md-5">Описание</th>
                        <th class="col-md-2">Цена</th>
                        <th class="col-md-2"></th>
                    </tr>
                </thead>
                <tbody>
                    @{ int count = 0;}
                    @foreach (var item in Model)
                    {
                        count++;

                        <tr class="row">
                            <th class="col-md-1">@count</th>
                            <td class="col-md-2">
                                @item.Name

                            </td>
                            <td class="col-md-5">@item.Description</td>
                            <td class="col-md-2">@item.Price лв</td>
                            <td class="col-md-2">


                                <form class="form-inline" asp-area="" asp-controller="Treatments" asp-action="Edit" asp-route-id="@item.Id" method="get">

                                    <button type="submit" class="btn harmony-bg-color ml-2">Редактирай</button>

                                </form>

                                <form class="form-inline" asp-area="" asp-controller="Treatments" asp-action="Delete" asp-route-id="@item.Id" method="get">

                                    <button type="submit" class="btn harmony-bg-color ml-2">Премахни</button>

                                </form>

                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <hr class="hr-4 mb-0" />
    </div>
</main>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}